//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(TypeName="attributes-content", Namespace="http://www.gexf.net/1.2draft")]
[XmlRoot("attributes", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
public partial class attributescontent {
    
    private attributecontent[] attributeField;
    
    private classtype classField;
    
    private modetype modeField;
    
    private bool modeFieldSpecified;
    
    private string startField;
    
    private string startopenField;
    
    private string endField;
    
    private string endopenField;
    
    /// <remarks/>
    [XmlElement("attribute")]
    public attributecontent[] attribute {
        get {
            return this.attributeField;
        }
        set {
            this.attributeField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public classtype @class {
        get {
            return this.classField;
        }
        set {
            this.classField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public modetype mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool modeSpecified {
        get {
            return this.modeFieldSpecified;
        }
        set {
            this.modeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string startopen {
        get {
            return this.startopenField;
        }
        set {
            this.startopenField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string endopen {
        get {
            return this.endopenField;
        }
        set {
            this.endopenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(TypeName="attribute-content", Namespace="http://www.gexf.net/1.2draft")]
[XmlRoot("attribute", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
public partial class attributecontent {
    
    private string[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    private string idField;
    
    private string titleField;
    
    private attrtypetype typeField;
    
    /// <remarks/>
    [XmlElement("default", typeof(string))]
    [XmlElement("options", typeof(string))]
    [XmlChoiceIdentifier("ItemsElementName")]
    public string[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("ItemsElementName")]
    [XmlIgnore()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public attrtypetype type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[XmlType(Namespace="http://www.gexf.net/1.2draft", IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    @default,
    
    /// <remarks/>
    options,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[XmlType(TypeName="attrtype-type", Namespace="http://www.gexf.net/1.2draft")]
public enum attrtypetype {
    
    /// <remarks/>
    integer,
    
    /// <remarks/>
    @long,
    
    /// <remarks/>
    @double,
    
    /// <remarks/>
    @float,
    
    /// <remarks/>
    boolean,
    
    /// <remarks/>
    liststring,
    
    /// <remarks/>
    @string,
    
    /// <remarks/>
    anyURI,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(TypeName="node-shape-content", Namespace="http://www.gexf.net/1.2draft/viz")]
public partial class nodeshapecontent {
    
    private spell[] spellsField;
    
    private nodeshapetype valueField;
    
    private string uriField;
    
    private string startField;
    
    private string startopenField;
    
    private string endField;
    
    private string endopenField;
    
    /// <remarks/>
    [XmlArrayItemAttribute("spell", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public spell[] spells {
        get {
            return this.spellsField;
        }
        set {
            this.spellsField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public nodeshapetype value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="anyURI")]
    public string uri {
        get {
            return this.uriField;
        }
        set {
            this.uriField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string startopen {
        get {
            return this.startopenField;
        }
        set {
            this.startopenField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string endopen {
        get {
            return this.endopenField;
        }
        set {
            this.endopenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://www.gexf.net/1.2draft")]
[XmlRoot(Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
public partial class spell {
    
    private string startField;
    
    private string startopenField;
    
    private string endField;
    
    private string endopenField;
    
    /// <remarks/>
    [XmlAttribute()]
    public string start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string startopen {
        get {
            return this.startopenField;
        }
        set {
            this.startopenField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string endopen {
        get {
            return this.endopenField;
        }
        set {
            this.endopenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[XmlType(TypeName="node-shape-type", Namespace="http://www.gexf.net/1.2draft/viz")]
public enum nodeshapetype {
    
    /// <remarks/>
    disc,
    
    /// <remarks/>
    square,
    
    /// <remarks/>
    triangle,
    
    /// <remarks/>
    diamond,
    
    /// <remarks/>
    image,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(TypeName="edge-shape-content", Namespace="http://www.gexf.net/1.2draft/viz")]
public partial class edgeshapecontent {
    
    private spell[] spellsField;
    
    private edgeshapetype valueField;
    
    private string startField;
    
    private string startopenField;
    
    private string endField;
    
    private string endopenField;
    
    /// <remarks/>
    [XmlArrayItemAttribute("spell", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public spell[] spells {
        get {
            return this.spellsField;
        }
        set {
            this.spellsField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public edgeshapetype value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string startopen {
        get {
            return this.startopenField;
        }
        set {
            this.startopenField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string endopen {
        get {
            return this.endopenField;
        }
        set {
            this.endopenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[XmlType(TypeName="edge-shape-type", Namespace="http://www.gexf.net/1.2draft/viz")]
public enum edgeshapetype {
    
    /// <remarks/>
    solid,
    
    /// <remarks/>
    dotted,
    
    /// <remarks/>
    dashed,
    
    /// <remarks/>
    @double,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(TypeName="edge-content", Namespace="http://www.gexf.net/1.2draft")]
[XmlRoot("edge", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
public partial class edgecontent {
    
    private object[] itemsField;
    
    private string startField;
    
    private string startopenField;
    
    private string endField;
    
    private string endopenField;
    
    private string idField;
    
    private edgetypetype typeField;
    
    private bool typeFieldSpecified;
    
    private string labelField;
    
    private string sourceField;
    
    private string targetField;
    
    private float weightField;
    
    private bool weightFieldSpecified;
    
    /// <remarks/>
    [XmlElement("attvalues", typeof(attvaluescontent))]
    [XmlElement("color", typeof(colorcontent))]
    [XmlElement("shape", typeof(edgeshapecontent))]
    [XmlElement("spells", typeof(spellscontent))]
    [XmlElement("thickness", typeof(thicknesscontent))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string startopen {
        get {
            return this.startopenField;
        }
        set {
            this.startopenField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string endopen {
        get {
            return this.endopenField;
        }
        set {
            this.endopenField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public edgetypetype type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="token")]
    public string label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public float weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool weightSpecified {
        get {
            return this.weightFieldSpecified;
        }
        set {
            this.weightFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(TypeName="attvalues-content", Namespace="http://www.gexf.net/1.2draft")]
[XmlRoot("attvalues", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
public partial class attvaluescontent {
    
    private attvalue[] attvalueField;
    
    /// <remarks/>
    [XmlElement("attvalue")]
    public attvalue[] attvalue {
        get {
            return this.attvalueField;
        }
        set {
            this.attvalueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://www.gexf.net/1.2draft")]
[XmlRoot(Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
public partial class attvalue {
    
    private string forField;
    
    private string valueField;
    
    private string startField;
    
    private string startopenField;
    
    private string endField;
    
    private string endopenField;
    
    /// <remarks/>
    [XmlAttribute()]
    public string @for {
        get {
            return this.forField;
        }
        set {
            this.forField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string startopen {
        get {
            return this.startopenField;
        }
        set {
            this.startopenField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string endopen {
        get {
            return this.endopenField;
        }
        set {
            this.endopenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(TypeName="color-content", Namespace="http://www.gexf.net/1.2draft/viz")]
[XmlRoot("color", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
public partial class colorcontent {
    
    private spell[] spellsField;
    
    private string rField;
    
    private string gField;
    
    private string bField;
    
    private float aField;
    
    private bool aFieldSpecified;
    
    private string startField;
    
    private string startopenField;
    
    private string endField;
    
    private string endopenField;
    
    /// <remarks/>
    [XmlArrayItemAttribute("spell", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public spell[] spells {
        get {
            return this.spellsField;
        }
        set {
            this.spellsField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string r {
        get {
            return this.rField;
        }
        set {
            this.rField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string g {
        get {
            return this.gField;
        }
        set {
            this.gField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string b {
        get {
            return this.bField;
        }
        set {
            this.bField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public float a {
        get {
            return this.aField;
        }
        set {
            this.aField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool aSpecified {
        get {
            return this.aFieldSpecified;
        }
        set {
            this.aFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string startopen {
        get {
            return this.startopenField;
        }
        set {
            this.startopenField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string endopen {
        get {
            return this.endopenField;
        }
        set {
            this.endopenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(TypeName="spells-content", Namespace="http://www.gexf.net/1.2draft")]
[XmlRoot("spells", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
public partial class spellscontent {
    
    private spell[] spellField;
    
    /// <remarks/>
    [XmlElement("spell")]
    public spell[] spell {
        get {
            return this.spellField;
        }
        set {
            this.spellField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(TypeName="thickness-content", Namespace="http://www.gexf.net/1.2draft/viz")]
[XmlRoot("thickness", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
public partial class thicknesscontent {
    
    private spell[] spellsField;
    
    private float valueField;
    
    private string startField;
    
    private string startopenField;
    
    private string endField;
    
    private string endopenField;
    
    /// <remarks/>
    [XmlArrayItemAttribute("spell", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public spell[] spells {
        get {
            return this.spellsField;
        }
        set {
            this.spellsField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public float value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string startopen {
        get {
            return this.startopenField;
        }
        set {
            this.startopenField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string endopen {
        get {
            return this.endopenField;
        }
        set {
            this.endopenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[XmlType(TypeName="edgetype-type", Namespace="http://www.gexf.net/1.2draft")]
public enum edgetypetype {
    
    /// <remarks/>
    directed,
    
    /// <remarks/>
    undirected,
    
    /// <remarks/>
    mutual,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(TypeName="node-content", Namespace="http://www.gexf.net/1.2draft")]
[XmlRoot("node", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
public partial class nodecontent {
    
    private object[] itemsField;
    
    private string startField;
    
    private string startopenField;
    
    private string endField;
    
    private string endopenField;
    
    private string pidField;
    
    private string idField;
    
    private string labelField;
    
    /// <remarks/>
    [XmlElement("attvalues", typeof(attvaluescontent))]
    [XmlElement("color", typeof(colorcontent))]
    [XmlElement("edges", typeof(edgescontent))]
    [XmlElement("nodes", typeof(nodescontent))]
    [XmlElement("parents", typeof(parentscontent))]
    [XmlElement("position", typeof(positioncontent))]
    [XmlElement("shape", typeof(nodeshapecontent))]
    [XmlElement("size", typeof(sizecontent))]
    [XmlElement("spells", typeof(spellscontent))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string startopen {
        get {
            return this.startopenField;
        }
        set {
            this.startopenField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string endopen {
        get {
            return this.endopenField;
        }
        set {
            this.endopenField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string pid {
        get {
            return this.pidField;
        }
        set {
            this.pidField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="token")]
    public string label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(TypeName="edges-content", Namespace="http://www.gexf.net/1.2draft")]
[XmlRoot("edges", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
public partial class edgescontent {
    
    private edgecontent[] edgeField;
    
    private string countField;
    
    /// <remarks/>
    [XmlElement("edge")]
    public edgecontent[] edge {
        get {
            return this.edgeField;
        }
        set {
            this.edgeField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(TypeName="nodes-content", Namespace="http://www.gexf.net/1.2draft")]
[XmlRoot("nodes", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
public partial class nodescontent {
    
    private nodecontent[] nodeField;
    
    private string countField;
    
    /// <remarks/>
    [XmlElement("node")]
    public nodecontent[] node {
        get {
            return this.nodeField;
        }
        set {
            this.nodeField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(TypeName="parents-content", Namespace="http://www.gexf.net/1.2draft")]
[XmlRoot("parents", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
public partial class parentscontent {
    
    private parent[] parentField;
    
    /// <remarks/>
    [XmlElement("parent")]
    public parent[] parent {
        get {
            return this.parentField;
        }
        set {
            this.parentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://www.gexf.net/1.2draft")]
[XmlRoot(Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
public partial class parent {
    
    private string forField;
    
    /// <remarks/>
    [XmlAttribute()]
    public string @for {
        get {
            return this.forField;
        }
        set {
            this.forField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(TypeName="position-content", Namespace="http://www.gexf.net/1.2draft/viz")]
[XmlRoot("position", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
public partial class positioncontent {
    
    private spell[] spellsField;
    
    private float xField;
    
    private float yField;
    
    private float zField;
    
    private string startField;
    
    private string startopenField;
    
    private string endField;
    
    private string endopenField;
    
    /// <remarks/>
    [XmlArrayItemAttribute("spell", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public spell[] spells {
        get {
            return this.spellsField;
        }
        set {
            this.spellsField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public float x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public float y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public float z {
        get {
            return this.zField;
        }
        set {
            this.zField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string startopen {
        get {
            return this.startopenField;
        }
        set {
            this.startopenField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string endopen {
        get {
            return this.endopenField;
        }
        set {
            this.endopenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(TypeName="size-content", Namespace="http://www.gexf.net/1.2draft/viz")]
[XmlRoot("size", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
public partial class sizecontent {
    
    private spell[] spellsField;
    
    private float valueField;
    
    private string startField;
    
    private string startopenField;
    
    private string endField;
    
    private string endopenField;
    
    /// <remarks/>
    [XmlArrayItemAttribute("spell", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public spell[] spells {
        get {
            return this.spellsField;
        }
        set {
            this.spellsField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public float value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string startopen {
        get {
            return this.startopenField;
        }
        set {
            this.startopenField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string endopen {
        get {
            return this.endopenField;
        }
        set {
            this.endopenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[XmlType(TypeName="class-type", Namespace="http://www.gexf.net/1.2draft")]
public enum classtype {
    
    /// <remarks/>
    node,
    
    /// <remarks/>
    edge,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[XmlType(TypeName="mode-type", Namespace="http://www.gexf.net/1.2draft")]
public enum modetype {
    
    /// <remarks/>
    @static,
    
    /// <remarks/>
    dynamic,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(TypeName="gexf-content", Namespace="http://www.gexf.net/1.2draft")]
[XmlRoot("gexf", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
public partial class gexfcontent {
    
    private metacontent metaField;
    
    private graphcontent graphField;
    
    private gexfcontentVersion versionField;
    
    private string variantField;
    
    /// <remarks/>
    public metacontent meta {
        get {
            return this.metaField;
        }
        set {
            this.metaField = value;
        }
    }
    
    /// <remarks/>
    public graphcontent graph {
        get {
            return this.graphField;
        }
        set {
            this.graphField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public gexfcontentVersion version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string variant {
        get {
            return this.variantField;
        }
        set {
            this.variantField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(TypeName="meta-content", Namespace="http://www.gexf.net/1.2draft")]
[XmlRoot("meta", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
public partial class metacontent {
    
    private string[] itemsField;
    
    private ItemsChoiceType1[] itemsElementNameField;
    
    private System.DateTime lastmodifieddateField;
    
    private bool lastmodifieddateFieldSpecified;
    
    /// <remarks/>
    [XmlElement("creator", typeof(string))]
    [XmlElement("description", typeof(string))]
    [XmlElement("keywords", typeof(string))]
    [XmlChoiceIdentifier("ItemsElementName")]
    public string[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("ItemsElementName")]
    [XmlIgnore()]
    public ItemsChoiceType1[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="date")]
    public System.DateTime lastmodifieddate {
        get {
            return this.lastmodifieddateField;
        }
        set {
            this.lastmodifieddateField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool lastmodifieddateSpecified {
        get {
            return this.lastmodifieddateFieldSpecified;
        }
        set {
            this.lastmodifieddateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[XmlType(Namespace="http://www.gexf.net/1.2draft", IncludeInSchema=false)]
public enum ItemsChoiceType1 {
    
    /// <remarks/>
    creator,
    
    /// <remarks/>
    description,
    
    /// <remarks/>
    keywords,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(TypeName="graph-content", Namespace="http://www.gexf.net/1.2draft")]
[XmlRoot("graph", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
public partial class graphcontent {
    
    private object[] itemsField;
    
    private timeformattype timeformatField;
    
    private bool timeformatFieldSpecified;
    
    private string startField;
    
    private string startopenField;
    
    private string endField;
    
    private string endopenField;
    
    private defaultedgetypetype defaultedgetypeField;
    
    private bool defaultedgetypeFieldSpecified;
    
    private idtypetype idtypeField;
    
    private bool idtypeFieldSpecified;
    
    private modetype modeField;
    
    private bool modeFieldSpecified;
    
    /// <remarks/>
    [XmlElement("attributes", typeof(attributescontent))]
    [XmlElement("edges", typeof(edgescontent))]
    [XmlElement("nodes", typeof(nodescontent))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public timeformattype timeformat {
        get {
            return this.timeformatField;
        }
        set {
            this.timeformatField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool timeformatSpecified {
        get {
            return this.timeformatFieldSpecified;
        }
        set {
            this.timeformatFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string startopen {
        get {
            return this.startopenField;
        }
        set {
            this.startopenField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string end {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string endopen {
        get {
            return this.endopenField;
        }
        set {
            this.endopenField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public defaultedgetypetype defaultedgetype {
        get {
            return this.defaultedgetypeField;
        }
        set {
            this.defaultedgetypeField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool defaultedgetypeSpecified {
        get {
            return this.defaultedgetypeFieldSpecified;
        }
        set {
            this.defaultedgetypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public idtypetype idtype {
        get {
            return this.idtypeField;
        }
        set {
            this.idtypeField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool idtypeSpecified {
        get {
            return this.idtypeFieldSpecified;
        }
        set {
            this.idtypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public modetype mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool modeSpecified {
        get {
            return this.modeFieldSpecified;
        }
        set {
            this.modeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[XmlType(TypeName="timeformat-type", Namespace="http://www.gexf.net/1.2draft")]
public enum timeformattype {
    
    /// <remarks/>
    integer,
    
    /// <remarks/>
    @double,
    
    /// <remarks/>
    date,
    
    /// <remarks/>
    dateTime,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[XmlType(TypeName="defaultedgetype-type", Namespace="http://www.gexf.net/1.2draft")]
public enum defaultedgetypetype {
    
    /// <remarks/>
    directed,
    
    /// <remarks/>
    undirected,
    
    /// <remarks/>
    mutual,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[XmlType(TypeName="idtype-type", Namespace="http://www.gexf.net/1.2draft")]
public enum idtypetype {
    
    /// <remarks/>
    integer,
    
    /// <remarks/>
    @string,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[XmlType(AnonymousType=true, Namespace="http://www.gexf.net/1.2draft")]
public enum gexfcontentVersion {
    
    /// <remarks/>
    [XmlEnumAttribute("1.2")]
    Item12,
}
